### PR TITLE
Added support for IAM Roles. 

### PR DESCRIPTION
**Pull request by cundohubs**
Added support for IAM Roles when access/secret keys are not set

Also, access/secret keys can be an option in a local properties file if testing locally.

### CODE REVIEW

**Comment by dhorions** [comment]
Hi,

I know I haven't been very responsive lately, but what was the reason for closing this pull request?

**Comment by cundohubs** [comment]
I included my own AWS keys by accident. :-(

Want me to submit another pull request w/o the sensitive data?

Facundo Nishiwaki

DevOps Engineer, CURALATE

206.778.4777. | facundo@curalate.com

2401 Walnut Street, Philadelphia, PA 19103

www.curalate.com
<http://t.signauxtrois.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs8qSMRqVf01Cl1qf-46VQsxsT56dBwGf2XRYjM02?t=http%3A%2F%2Fwww.curalate.com%2F&si=5713909304524800&pi=5041472c-9d9b-4c4f-f52c-c10c5027da29>

**Comment by dhorions** [comment]
That would be great, thanks.

**Comment by cundohubs** [comment]
I made another big change since then:
- separate configuration files into one config file per table instead of
  one consolidated file for all tables. I figured this would prevent common
  human errors and be easier to read when there's a large amount of tables
  that will be scaled in this manner.

Would you like this as well or or just the IAM Role support? (hint: IAM
Role support only requires removing AWS access/secret keys references in
the code)

Facundo

DevOps Engineer, CURALATE

**Comment by dhorions** [comment]
Hi,

Both seem like good additions.  Thanks a lot for the effort.

**Pull request closed without merging**
